### PR TITLE
Update es5.jj

### PR DESCRIPTION
**Pull request by wener-tiobe**
## Describe the PR

Fixes lexical errors by adding ignoring these unknown characters. These will only appear in text, not in code.

## Related issues

[34321](https://redmine.tiobe.com/issues/34321)
[32344](https://redmine.tiobe.com/issues/32344)
[27270](https://redmine.tiobe.com/issues/27270)
[25637](https://redmine.tiobe.com/issues/25637)

### CODE REVIEW

**Comment by wener-tiobe** [comment]
Also logged in [32872: Bring PMD back in line with main repository](https://redmine.tiobe.com/issues/32872) as todo.

**Review by brouwers-tiobe — APPROVED** [review]

**Comment by it-tiobe** [comment]
## Build artifact: CPD
  |Tool|Download|
  |---|---|
  |CPD|[CPD-0.1.0+272.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/pmd/PR_19/Package%20PMD%20checkers/run_37/attempt_1/CPD-0.1.0+272.zip)|

**Comment by it-tiobe** [comment]
## Build artifact: pmd
  |Tool|Download|
  |---|---|
  |pmd|[pmd-0.1.0+272.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/pmd/PR_19/Package%20PMD%20checkers/run_37/attempt_1/pmd-0.1.0+272.zip)|

**Comment by it-tiobe** [comment]
## Build artifact: CPD
  |Tool|Download|
  |---|---|
  |CPD|[CPD-0.1.0+272.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/pmd/PR_19/Package%20PMD%20checkers/run_38/attempt_1/CPD-0.1.0+272.zip)|

**Comment by it-tiobe** [comment]
## Build artifact: pmd
  |Tool|Download|
  |---|---|
  |pmd|[pmd-0.1.0+272.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/pmd/PR_19/Package%20PMD%20checkers/run_38/attempt_1/pmd-0.1.0+272.zip)|

**Comment by it-tiobe** [comment]
## Build artifact: pmd
  |Tool|Download|
  |---|---|
  |pmd|[pmd-0.1.0+272.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/pmd/PR_19/Package%20PMD%20checkers/run_40/attempt_1/pmd-0.1.0+272.zip)|

**Comment by it-tiobe** [comment]
## Build artifact: CPD
  |Tool|Download|
  |---|---|
  |CPD|[CPD-0.1.0+272.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/pmd/PR_19/Package%20PMD%20checkers/run_40/attempt_1/CPD-0.1.0+272.zip)|

**Comment by it-tiobe** [comment]
## Build artifact: CPD
  |Tool|Download|
  |---|---|
  |CPD|[CPD-0.1.0+272.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/pmd/PR_19/Package%20PMD%20checkers/run_41/attempt_1/CPD-0.1.0+272.zip)|

**Comment by it-tiobe** [comment]
## Build artifact: pmd
  |Tool|Download|
  |---|---|
  |pmd|[pmd-0.1.0+272.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/pmd/PR_19/Package%20PMD%20checkers/run_41/attempt_1/pmd-0.1.0+272.zip)|

**Pull request merged**
